// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 10);
user_pref("app.normandy.user_id", "df280af1-b87d-4b0c-86a9-95535f1452ec");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1709910149);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1709910389);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1709910509);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1709910001);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1709310762);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1709910029);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1709310671);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1709910269);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 21100);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1709310612);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 96);
user_pref("browser.newtabpage.activity-stream.impressionId", "{faf7773e-fa59-408a-abeb-d6a54c3d34b6}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20210927121355");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1709910001");
user_pref("browser.slowStartup.averageTime", 10954);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20210927121355");
user_pref("browser.startup.homepage_override.mstone", "78.15.0");
user_pref("browser.startup.lastColdStartupCheck", 1709910000);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1709310620177");
user_pref("distribution.iniFile.exists.appversion", "78.15.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "1a5646a980da469c903d061c6e65c2f3");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.cache.lastUpdate", 1709910182);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20210927121355");
user_pref("extensions.lastAppVersion", "78.15.0");
user_pref("extensions.lastPlatformVersion", "78.15.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{f7617162-0602-4b50-87f3-e572ccf08e1b}\",\"addons\":{\"proxy-failover@mozilla.com\":{\"version\":\"1.0.1\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"d846eef4-6646-45d5-80e7-7b25f64d396b\",\"formautofill@mozilla.org\":\"cc59f040-faa2-441e-a6da-9f74b68a27ed\",\"screenshots@mozilla.org\":\"ac58146d-aeab-4c15-9913-ab08d4349170\",\"webcompat-reporter@mozilla.org\":\"c8150c5b-d823-4848-b131-0216af9ffd3f\",\"webcompat@mozilla.org\":\"023ca8a8-28f2-458a-9dfa-6a910200965d\",\"default-theme@mozilla.org\":\"173dd8d4-76d8-4eaf-91e3-818d7e38ed10\",\"google@search.mozilla.org\":\"dc512b0e-f028-40ba-a4ff-2ba3ede2344b\",\"wikipedia@search.mozilla.org\":\"c2229277-ac3f-4632-a5c4-f7de06c750a2\",\"bing@search.mozilla.org\":\"c8529e75-d2e6-467a-83a5-19e7f06ca631\",\"ddg@search.mozilla.org\":\"b3d86bac-aa45-4da7-96df-e13d783d89ad\",\"ebay@search.mozilla.org\":\"8e380e6b-ec45-4a1d-a0f5-35c68c4afb26\",\"qwant@search.mozilla.org\":\"eb459a22-e21c-44cf-b90c-796f1ed84b0b\",\"proxy-failover@mozilla.com\":\"5cff6eae-2899-41ce-8a4a-bf7c9cf6a9ce\"}");
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("idle.lastDailyNotification", 1709910372);
user_pref("media.gmp-manager.buildID", "20210927121355");
user_pref("media.gmp-manager.lastCheck", 1709910172);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.database.lastMaintenance", 1709910372);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.purge_trackers.date_in_cookie_database", "0");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "74413c69-9478-410c-9a1a-a672ce15a676");
user_pref("security.sandbox.plugin.tempDirSuffix", "4e9a9d37-cc16-4c6b-b01b-2ecebc9dde34");
user_pref("services.blocklist.addons-mlbf.checked", 1709910028);
user_pref("services.blocklist.gfx.checked", 1709910028);
user_pref("services.blocklist.plugins.checked", 1709910028);
user_pref("services.settings.clock_skew_seconds", 1);
user_pref("services.settings.last_etag", "\"1709903009354\"");
user_pref("services.settings.last_update_seconds", 1709910028);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1709910028);
user_pref("services.settings.main.cfr.last_check", 1709910028);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1709910028);
user_pref("services.settings.main.hijack-blocklists.last_check", 1709910028);
user_pref("services.settings.main.language-dictionaries.last_check", 1709910028);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1709910006);
user_pref("services.settings.main.search-config.last_check", 1709910028);
user_pref("services.settings.main.search-default-override-allowlist.last_check", 1709910028);
user_pref("services.settings.main.sites-classification.last_check", 1709910028);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1709910028);
user_pref("services.settings.main.whats-new-panel.last_check", 1709910028);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1709910372);
user_pref("toolkit.startup.last_success", 1709909997);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20210927121355");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
